//! SSH certificate primitives shared by MCP issuance and the SSH transport.
//!
//! Private keys in this module are server host/CA keys. Client private keys are
//! deliberately never accepted or generated by COG.

use crate::{crypto::SecretBox, db::Database};
use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use ssh_key::{Algorithm, LineEnding, PrivateKey, PublicKey, certificate};

pub const PRINCIPAL: &str = "cog-git";
pub const MAX_PUBLIC_KEY_BYTES: usize = 1024;

pub struct KeySet {
    pub host: PrivateKey,
    pub user_ca: PrivateKey,
}

impl KeySet {
    pub fn load_or_create(db: &Database, secrets: &SecretBox) -> anyhow::Result<Self> {
        Ok(Self {
            host: load_or_create_key(db, secrets, "host")?,
            user_ca: load_or_create_key(db, secrets, "user_ca")?,
        })
    }
}

fn load_or_create_key(
    db: &Database,
    secrets: &SecretBox,
    purpose: &str,
) -> anyhow::Result<PrivateKey> {
    let record = match db.active_ssh_key(purpose)? {
        Some(record) => record,
        None => {
            let generated = generate_key()?;
            let public = generated.public_key().to_openssh()?;
            let encrypted = secrets.seal(&encode_private(&generated)?)?;
            db.install_initial_ssh_key(purpose, &public, &encrypted)?
        }
    };
    anyhow::ensure!(
        record.algorithm == "ssh-ed25519",
        "unsupported durable SSH key algorithm"
    );
    let private = decode_private(&secrets.open(&record.private_ciphertext)?).map_err(|_| {
        anyhow::anyhow!(
            "active {purpose} SSH key cannot be decrypted; restore the matching COG master key"
        )
    })?;
    anyhow::ensure!(
        private.public_key().to_openssh()? == record.public_key,
        "active {purpose} SSH key does not match its public key"
    );
    Ok(private)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Service {
    UploadPack,
    ReceivePack,
}

impl Service {
    pub fn permission(self) -> &'static str {
        match self {
            Self::UploadPack => "read",
            Self::ReceivePack => "write",
        }
    }
}

/// Parse exactly the command emitted by stock Git. No shell parser is used.
pub fn parse_command(command: &str) -> anyhow::Result<(Service, String)> {
    anyhow::ensure!(!command.contains(['\r', '\n', '\0']), "invalid SSH command");
    let (service, argument) = command
        .split_once(' ')
        .ok_or_else(|| anyhow::anyhow!("unsupported SSH command"))?;
    let service = match service {
        "git-upload-pack" => Service::UploadPack,
        "git-receive-pack" => Service::ReceivePack,
        _ => anyhow::bail!("unsupported SSH command"),
    };
    anyhow::ensure!(
        argument.starts_with('\'') && argument.ends_with('\'') && argument.len() > 2,
        "repository must be one single-quoted opaque ID"
    );
    let repository = argument[1..argument.len() - 1]
        .strip_prefix('/')
        .unwrap_or(&argument[1..argument.len() - 1]);
    anyhow::ensure!(
        !repository.contains('\'') && crate::git::valid_repository_id(repository),
        "invalid repository ID"
    );
    Ok((service, repository.to_owned()))
}

pub fn parse_git_protocol(value: &str) -> anyhow::Result<Option<&str>> {
    match value {
        "" => Ok(None),
        "version=0" | "version=1" | "version=2" => Ok(Some(value)),
        _ => anyhow::bail!("unsupported GIT_PROTOCOL value"),
    }
}

pub fn parse_public_key(input: &str) -> anyhow::Result<PublicKey> {
    anyhow::ensure!(
        input.len() <= MAX_PUBLIC_KEY_BYTES,
        "public key is too large"
    );
    anyhow::ensure!(input == input.trim(), "public key contains trailing data");
    anyhow::ensure!(
        input.split_ascii_whitespace().count() == 2,
        "public key comments are not accepted"
    );
    let key = PublicKey::from_openssh(input)
        .map_err(|_| anyhow::anyhow!("invalid OpenSSH public key"))?;
    anyhow::ensure!(
        key.algorithm() == Algorithm::Ed25519,
        "only Ed25519 public keys are supported"
    );
    anyhow::ensure!(
        key.to_openssh()? == input,
        "public key must use canonical OpenSSH encoding"
    );
    Ok(key)
}

pub fn fingerprint(key: &PublicKey) -> String {
    key.fingerprint(ssh_key::HashAlg::Sha256).to_string()
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Binding {
    pub version: u8,
    pub issuance_id: String,
    pub user_id: String,
    pub identity_id: String,
    pub agent_id: String,
    pub client_id: String,
    pub integration_id: String,
    pub repository_id: String,
    pub permission: String,
    pub fingerprint: String,
    pub issued_at: i64,
    pub expires_at: i64,
}

pub fn encode_binding(binding: &Binding) -> anyhow::Result<String> {
    let bytes = serde_json::to_vec(binding)?;
    anyhow::ensure!(bytes.len() <= 768, "certificate binding is too large");
    Ok(format!("cog-v1:{}", URL_SAFE_NO_PAD.encode(bytes)))
}

pub fn decode_binding(key_id: &str) -> anyhow::Result<Binding> {
    let encoded = key_id
        .strip_prefix("cog-v1:")
        .ok_or_else(|| anyhow::anyhow!("unknown certificate binding version"))?;
    anyhow::ensure!(encoded.len() <= 1024, "certificate binding is too large");
    let binding: Binding = serde_json::from_slice(&URL_SAFE_NO_PAD.decode(encoded)?)?;
    anyhow::ensure!(binding.version == 1, "unknown certificate binding version");
    Ok(binding)
}

pub fn generate_key() -> anyhow::Result<PrivateKey> {
    Ok(PrivateKey::random(
        &mut rand::rngs::OsRng,
        Algorithm::Ed25519,
    )?)
}

pub fn encode_private(key: &PrivateKey) -> anyhow::Result<Vec<u8>> {
    Ok(key.to_openssh(LineEnding::LF)?.as_bytes().to_vec())
}

pub fn decode_private(bytes: &[u8]) -> anyhow::Result<PrivateKey> {
    Ok(PrivateKey::from_openssh(bytes)?)
}

pub fn sign(
    ca: &PrivateKey,
    subject: &PublicKey,
    binding: &Binding,
    serial: u64,
) -> anyhow::Result<String> {
    let valid_after = binding.issued_at.saturating_sub(30) as u64;
    let valid_before = binding.expires_at as u64;
    let mut builder = certificate::Builder::new_with_random_nonce(
        &mut rand::rngs::OsRng,
        subject.key_data().clone(),
        valid_after,
        valid_before,
    )?;
    builder
        .serial(serial)?
        .cert_type(certificate::CertType::User)?
        .key_id(encode_binding(binding)?)?
        .valid_principal(PRINCIPAL)?;
    // Intentionally add no OpenSSH permission extensions. In particular this
    // omits agent/port/X11 forwarding, PTY, user-rc, and arbitrary environment.
    Ok(builder.sign(ca)?.to_openssh()?)
}

/// Parse and cryptographically verify a COG user certificate before its
/// binding is trusted by a downstream transport.
pub fn verify_certificate(
    encoded: &str,
    ca: &PublicKey,
    subject: &PublicKey,
    now: i64,
) -> anyhow::Result<Binding> {
    let certificate = ssh_key::Certificate::from_openssh(encoded)
        .map_err(|_| anyhow::anyhow!("invalid OpenSSH certificate"))?;
    let ca_fingerprint = ca.fingerprint(ssh_key::HashAlg::Sha256);
    certificate
        .validate_at(
            now.try_into()
                .map_err(|_| anyhow::anyhow!("invalid time"))?,
            [&ca_fingerprint],
        )
        .map_err(|_| anyhow::anyhow!("SSH certificate verification failed"))?;
    anyhow::ensure!(
        certificate.cert_type() == certificate::CertType::User,
        "SSH certificate is not a user certificate"
    );
    anyhow::ensure!(
        certificate.valid_principals() == [PRINCIPAL],
        "SSH certificate has invalid principals"
    );
    anyhow::ensure!(
        certificate.public_key() == subject.key_data(),
        "SSH certificate does not match the authenticated public key"
    );
    anyhow::ensure!(
        certificate.critical_options().is_empty() && certificate.extensions().is_empty(),
        "SSH certificate contains unsupported permissions"
    );
    let binding = decode_binding(certificate.key_id())?;
    anyhow::ensure!(binding.issued_at <= now, "SSH certificate is not yet valid");
    anyhow::ensure!(binding.expires_at > now, "SSH certificate has expired");
    anyhow::ensure!(
        binding.fingerprint == fingerprint(subject),
        "SSH certificate fingerprint binding does not match"
    );
    anyhow::ensure!(
        matches!(binding.permission.as_str(), "read" | "write"),
        "SSH certificate permission is invalid"
    );
    anyhow::ensure!(
        crate::git::valid_repository_id(&binding.repository_id),
        "SSH certificate repository binding is invalid"
    );
    Ok(binding)
}

pub fn verify_certificate_with_durable_cas(
    encoded: &str,
    db: &Database,
    subject: &PublicKey,
    now: i64,
) -> anyhow::Result<Binding> {
    let mut last_error = None;
    for record in db.ssh_keys()?.into_iter().filter(|record| {
        record.purpose == "user_ca"
            && (record.active || record.retirement_time.is_some_and(|until| until > now))
    }) {
        let ca = PublicKey::from_openssh(&record.public_key)
            .map_err(|_| anyhow::anyhow!("durable SSH CA public key is unreadable"))?;
        match verify_certificate(encoded, &ca, subject, now) {
            Ok(binding) => return Ok(binding),
            Err(error) => last_error = Some(error),
        }
    }
    Err(last_error.unwrap_or_else(|| anyhow::anyhow!("no valid SSH user CA is available")))
}

pub fn stable_serial(issuance_id: &str) -> u64 {
    let digest = Sha256::digest(issuance_id.as_bytes());
    u64::from_be_bytes(digest[..8].try_into().expect("eight-byte digest prefix"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(unix)]
    #[derive(Clone)]
    struct InteropServer {
        ca: PublicKey,
    }

    #[cfg(unix)]
    impl russh::server::Server for InteropServer {
        type Handler = Self;

        fn new_client(&mut self, _peer_addr: Option<std::net::SocketAddr>) -> Self::Handler {
            self.clone()
        }
    }

    #[cfg(unix)]
    impl russh::server::Handler for InteropServer {
        type Error = anyhow::Error;

        async fn auth_openssh_certificate(
            &mut self,
            user: &str,
            certificate: &russh::keys::Certificate,
        ) -> Result<russh::server::Auth, Self::Error> {
            let encoded = certificate.to_openssh()?;
            let subject =
                russh::keys::PublicKey::new(certificate.public_key().clone(), "").to_openssh()?;
            let subject = parse_public_key(&subject)?;
            Ok(
                if user == "git"
                    && verify_certificate(
                        &encoded,
                        &self.ca,
                        &subject,
                        chrono::Utc::now().timestamp(),
                    )
                    .is_ok()
                {
                    russh::server::Auth::Accept
                } else {
                    russh::server::Auth::reject()
                },
            )
        }

        async fn channel_open_session(
            &mut self,
            _channel: russh::Channel<russh::server::Msg>,
            _session: &mut russh::server::Session,
        ) -> Result<bool, Self::Error> {
            Ok(true)
        }

        async fn exec_request(
            &mut self,
            channel: russh::ChannelId,
            command: &[u8],
            session: &mut russh::server::Session,
        ) -> Result<(), Self::Error> {
            if parse_command(std::str::from_utf8(command)?).is_ok() {
                let _ = session.channel_success(channel);
                session.data(channel, bytes::Bytes::from_static(b"interop-ok\n"))?;
                session.exit_status_request(channel, 0)?;
            } else {
                let _ = session.channel_failure(channel);
                session.exit_status_request(channel, 1)?;
            }
            session.eof(channel)?;
            session.close(channel)?;
            Ok(())
        }
    }

    #[test]
    fn command_parser_is_exact() {
        let id = "550e8400-e29b-41d4-a716-446655440000";
        assert_eq!(
            parse_command(&format!("git-upload-pack '{id}'")).unwrap(),
            (Service::UploadPack, id.into())
        );
        assert_eq!(
            parse_command(&format!("git-upload-pack '/{id}'")).unwrap(),
            (Service::UploadPack, id.into())
        );
        for bad in [
            "sh",
            "git-upload-pack x",
            "git-upload-pack '../x'",
            "git-upload-pack '550e8400-e29b-41d4-a716-446655440000' extra",
            "git receive-pack '550e8400-e29b-41d4-a716-446655440000'",
        ] {
            assert!(parse_command(bad).is_err(), "accepted {bad:?}");
        }
    }

    #[test]
    fn ed25519_certificate_round_trip() {
        let ca = generate_key().unwrap();
        let subject = generate_key().unwrap();
        let now = chrono::Utc::now().timestamp();
        let binding = Binding {
            version: 1,
            issuance_id: uuid::Uuid::new_v4().to_string(),
            user_id: "u".into(),
            identity_id: "i".into(),
            agent_id: "a".into(),
            client_id: "c".into(),
            integration_id: "n".into(),
            repository_id: "550e8400-e29b-41d4-a716-446655440000".into(),
            permission: "read".into(),
            fingerprint: fingerprint(subject.public_key()),
            issued_at: now,
            expires_at: now + 900,
        };
        let encoded = sign(
            &ca,
            subject.public_key(),
            &binding,
            stable_serial(&binding.issuance_id),
        )
        .unwrap();
        let cert = ssh_key::Certificate::from_openssh(&encoded).unwrap();
        assert_eq!(decode_binding(cert.key_id()).unwrap(), binding);
        assert_eq!(cert.valid_principals(), &[PRINCIPAL]);
        assert_eq!(
            verify_certificate(&encoded, ca.public_key(), subject.public_key(), now).unwrap(),
            binding
        );
        assert!(
            verify_certificate(
                &encoded,
                generate_key().unwrap().public_key(),
                subject.public_key(),
                now
            )
            .is_err()
        );
        assert!(
            verify_certificate(
                &encoded,
                ca.public_key(),
                generate_key().unwrap().public_key(),
                now
            )
            .is_err()
        );
        assert!(
            verify_certificate(&encoded, ca.public_key(), subject.public_key(), now + 901).is_err()
        );
    }

    #[test]
    fn public_keys_must_be_canonical_ed25519_without_comments() {
        let key = generate_key().unwrap().public_key().to_openssh().unwrap();
        assert!(parse_public_key(&key).is_ok());
        assert!(parse_public_key(&format!("{key} comment")).is_err());
        assert!(parse_public_key(&key.replace(' ', "  ")).is_err());
        assert!(parse_public_key(&format!("{key}\n")).is_err());
        assert!(parse_public_key(&"x".repeat(MAX_PUBLIC_KEY_BYTES + 1)).is_err());
    }

    proptest::proptest! {
        #[test]
        fn parsers_never_panic(input in ".{0,4096}") {
            let _ = parse_command(&input);
            let _ = parse_git_protocol(&input);
            let _ = parse_public_key(&input);
            let _ = decode_binding(&input);
        }
    }

    #[test]
    fn durable_keys_survive_restart_and_wrong_master_key_fails_closed() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("cog.sqlite");
        let secrets = SecretBox::new(b"0123456789abcdef0123456789abcdef");
        let first = KeySet::load_or_create(&Database::open(&path).unwrap(), &secrets).unwrap();
        let first_host = first.host.public_key().to_openssh().unwrap();
        let first_ca = first.user_ca.public_key().to_openssh().unwrap();
        drop(first);
        let second = KeySet::load_or_create(&Database::open(&path).unwrap(), &secrets).unwrap();
        assert_eq!(second.host.public_key().to_openssh().unwrap(), first_host);
        assert_eq!(second.user_ca.public_key().to_openssh().unwrap(), first_ca);
        let wrong = SecretBox::new(b"fedcba9876543210fedcba9876543210");
        assert!(KeySet::load_or_create(&Database::open(&path).unwrap(), &wrong).is_err());
    }

    #[test]
    fn ca_rotation_overlaps_existing_certificates_and_retires_after_deadline() {
        let directory = tempfile::tempdir().unwrap();
        let database = Database::open(&directory.path().join("cog.sqlite")).unwrap();
        let secrets = SecretBox::new(b"0123456789abcdef0123456789abcdef");
        let original = KeySet::load_or_create(&database, &secrets).unwrap();
        let subject = generate_key().unwrap();
        let now = chrono::Utc::now().timestamp();
        let binding = Binding {
            version: 1,
            issuance_id: uuid::Uuid::new_v4().to_string(),
            user_id: "user".into(),
            identity_id: "identity".into(),
            agent_id: "agent".into(),
            client_id: "client".into(),
            integration_id: "integration".into(),
            repository_id: "550e8400-e29b-41d4-a716-446655440000".into(),
            permission: "read".into(),
            fingerprint: fingerprint(subject.public_key()),
            issued_at: now,
            expires_at: now + 300,
        };
        let certificate = sign(
            &original.user_ca,
            subject.public_key(),
            &binding,
            stable_serial(&binding.issuance_id),
        )
        .unwrap();
        let replacement = generate_key().unwrap();
        let prepared = database
            .prepare_ssh_key(
                "user_ca",
                &replacement.public_key().to_openssh().unwrap(),
                &secrets
                    .seal(&encode_private(&replacement).unwrap())
                    .unwrap(),
            )
            .unwrap();
        database
            .activate_ssh_key(&prepared.id, "user_ca", now + 301)
            .unwrap();
        assert_eq!(
            verify_certificate_with_durable_cas(&certificate, &database, subject.public_key(), now)
                .unwrap(),
            binding
        );
        let retiring = database
            .ssh_keys()
            .unwrap()
            .into_iter()
            .find(|key| key.purpose == "user_ca" && !key.active)
            .unwrap();
        assert!(database.retire_ssh_key(&retiring.id, now + 300).is_err());
        database.retire_ssh_key(&retiring.id, now + 301).unwrap();
        assert!(
            verify_certificate_with_durable_cas(&certificate, &database, subject.public_key(), now)
                .is_err()
        );
    }

    #[test]
    fn certificate_clock_and_repository_boundaries_fail_closed() {
        let ca = generate_key().unwrap();
        let subject = generate_key().unwrap();
        let now = chrono::Utc::now().timestamp();
        let mut binding = Binding {
            version: 1,
            issuance_id: uuid::Uuid::new_v4().to_string(),
            user_id: "u".into(),
            identity_id: "i".into(),
            agent_id: "a".into(),
            client_id: "c".into(),
            integration_id: "n".into(),
            repository_id: "550e8400-e29b-41d4-a716-446655440000".into(),
            permission: "read".into(),
            fingerprint: fingerprint(subject.public_key()),
            issued_at: now + 60,
            expires_at: now + 120,
        };
        let future = sign(&ca, subject.public_key(), &binding, 1).unwrap();
        assert!(verify_certificate(&future, ca.public_key(), subject.public_key(), now).is_err());
        binding.issued_at = now;
        binding.expires_at = now + 60;
        binding.repository_id = "../repository".into();
        let invalid_repository = sign(&ca, subject.public_key(), &binding, 2).unwrap();
        assert!(
            verify_certificate(
                &invalid_repository,
                ca.public_key(),
                subject.public_key(),
                now
            )
            .is_err()
        );
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn stock_openssh_authenticates_rust_signed_certificate_and_executes() {
        use russh::server::Server as _;
        use std::os::unix::fs::PermissionsExt;

        if std::process::Command::new("ssh")
            .arg("-V")
            .output()
            .is_err()
        {
            return;
        }
        let directory = tempfile::tempdir().unwrap();
        let ca = generate_key().unwrap();
        let subject = generate_key().unwrap();
        let host = generate_key().unwrap();
        let now = chrono::Utc::now().timestamp();
        let repository = "550e8400-e29b-41d4-a716-446655440000";
        let binding = Binding {
            version: 1,
            issuance_id: uuid::Uuid::new_v4().to_string(),
            user_id: "user".into(),
            identity_id: "identity".into(),
            agent_id: "agent".into(),
            client_id: "client".into(),
            integration_id: "integration".into(),
            repository_id: repository.into(),
            permission: "read".into(),
            fingerprint: fingerprint(subject.public_key()),
            issued_at: now,
            expires_at: now + 900,
        };
        let certificate = sign(
            &ca,
            subject.public_key(),
            &binding,
            stable_serial(&binding.issuance_id),
        )
        .unwrap();
        let private_path = directory.path().join("id_ed25519");
        let certificate_path = directory.path().join("id_ed25519-cert.pub");
        let known_hosts_path = directory.path().join("known_hosts");
        std::fs::write(&private_path, encode_private(&subject).unwrap()).unwrap();
        std::fs::set_permissions(&private_path, std::fs::Permissions::from_mode(0o600)).unwrap();
        std::fs::write(&certificate_path, format!("{certificate}\n")).unwrap();

        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let port = listener.local_addr().unwrap().port();
        std::fs::write(
            &known_hosts_path,
            format!(
                "[127.0.0.1]:{port} {}\n",
                host.public_key().to_openssh().unwrap()
            ),
        )
        .unwrap();
        let host_key =
            russh::keys::PrivateKey::from_openssh(encode_private(&host).unwrap()).unwrap();
        let config = std::sync::Arc::new(russh::server::Config {
            methods: russh::MethodSet::from(&[russh::MethodKind::PublicKey][..]),
            keys: vec![host_key],
            ..Default::default()
        });
        let ca_public = ca.public_key().clone();
        let task = tokio::spawn(async move {
            let mut server = InteropServer { ca: ca_public };
            server.run_on_socket(config, &listener).await
        });
        let output = tokio::process::Command::new("ssh")
            .args([
                "-F",
                "/dev/null",
                "-o",
                "BatchMode=yes",
                "-o",
                "IdentitiesOnly=yes",
                "-o",
                "StrictHostKeyChecking=yes",
                "-o",
                &format!("UserKnownHostsFile={}", known_hosts_path.display()),
                "-i",
                private_path.to_str().unwrap(),
                "-p",
                &port.to_string(),
                "git@127.0.0.1",
                &format!("git-upload-pack '{repository}'"),
            ])
            .output()
            .await
            .unwrap();
        task.abort();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(output.stdout, b"interop-ok\n");
    }
}
