//! SSH certificate primitives shared by MCP issuance and the SSH transport.
//!
//! Private keys in this module are server host/CA keys. Client private keys are
//! deliberately never accepted or generated by COG.

use crate::{crypto::SecretBox, db::Database};
use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use ssh_key::{Algorithm, LineEnding, PrivateKey, PublicKey, certificate};

pub const PRINCIPAL: &str = "cog-git";
pub const MAX_PUBLIC_KEY_BYTES: usize = 1024;

pub struct KeySet {
    pub host: PrivateKey,
    pub user_ca: PrivateKey,
}

impl KeySet {
    pub fn load_or_create(db: &Database, secrets: &SecretBox) -> anyhow::Result<Self> {
        Ok(Self {
            host: load_or_create_key(db, secrets, "host")?,
            user_ca: load_or_create_key(db, secrets, "user_ca")?,
        })
    }
}

fn load_or_create_key(
    db: &Database,
    secrets: &SecretBox,
    purpose: &str,
) -> anyhow::Result<PrivateKey> {
    let record = match db.active_ssh_key(purpose)? {
        Some(record) => record,
        None => {
            let generated = generate_key()?;
            let public = generated.public_key().to_openssh()?;
            let encrypted = secrets.seal(&encode_private(&generated)?)?;
            db.install_initial_ssh_key(purpose, &public, &encrypted)?
        }
    };
    anyhow::ensure!(
        record.algorithm == "ssh-ed25519",
        "unsupported durable SSH key algorithm"
    );
    let private = decode_private(&secrets.open(&record.private_ciphertext)?).map_err(|_| {
        anyhow::anyhow!(
            "active {purpose} SSH key cannot be decrypted; restore the matching COG master key"
        )
    })?;
    anyhow::ensure!(
        private.public_key().to_openssh()? == record.public_key,
        "active {purpose} SSH key does not match its public key"
    );
    Ok(private)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Service {
    UploadPack,
    ReceivePack,
}

impl Service {
    pub fn permission(self) -> &'static str {
        match self {
            Self::UploadPack => "read",
            Self::ReceivePack => "write",
        }
    }
}

/// Parse exactly the command emitted by stock Git. No shell parser is used.
pub fn parse_command(command: &str) -> anyhow::Result<(Service, String)> {
    anyhow::ensure!(!command.contains(['\r', '\n', '\0']), "invalid SSH command");
    let (service, argument) = command
        .split_once(' ')
        .ok_or_else(|| anyhow::anyhow!("unsupported SSH command"))?;
    let service = match service {
        "git-upload-pack" => Service::UploadPack,
        "git-receive-pack" => Service::ReceivePack,
        _ => anyhow::bail!("unsupported SSH command"),
    };
    anyhow::ensure!(
        argument.starts_with('\'') && argument.ends_with('\'') && argument.len() > 2,
        "repository must be one single-quoted opaque ID"
    );
    let repository = argument[1..argument.len() - 1]
        .strip_prefix('/')
        .unwrap_or(&argument[1..argument.len() - 1]);
    anyhow::ensure!(
        !repository.contains('\'') && crate::git::valid_repository_id(repository),
        "invalid repository ID"
    );
    Ok((service, repository.to_owned()))
}

pub fn parse_git_protocol(value: &str) -> anyhow::Result<Option<&str>> {
    match value {
        "" => Ok(None),
        "version=0" | "version=1" | "version=2" => Ok(Some(value)),
        _ => anyhow::bail!("unsupported GIT_PROTOCOL value"),
    }
}

pub fn parse_public_key(input: &str) -> anyhow::Result<PublicKey> {
    anyhow::ensure!(
        input.len() <= MAX_PUBLIC_KEY_BYTES,
        "public key is too large"
    );
    anyhow::ensure!(input == input.trim(), "public key contains trailing data");
    anyhow::ensure!(
        input.split_ascii_whitespace().count() == 2,
        "public key comments are not accepted"
    );
    let key = PublicKey::from_openssh(input)
        .map_err(|_| anyhow::anyhow!("invalid OpenSSH public key"))?;
    anyhow::ensure!(
        key.algorithm() == Algorithm::Ed25519,
        "only Ed25519 public keys are supported"
    );
    anyhow::ensure!(
        key.to_openssh()? == input,
        "public key must use canonical OpenSSH encoding"
    );
    Ok(key)
}

pub fn fingerprint(key: &PublicKey) -> String {
    key.fingerprint(ssh_key::HashAlg::Sha256).to_string()
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Binding {
    pub version: u8,
    pub issuance_id: String,
    pub user_id: String,
    pub identity_id: String,
    pub agent_id: String,
    pub client_id: String,
    pub integration_id: String,
    pub repository_id: String,
    pub permission: String,
    pub fingerprint: String,
    pub issued_at: i64,
    pub expires_at: i64,
}

pub fn encode_binding(binding: &Binding) -> anyhow::Result<String> {
    let bytes = serde_json::to_vec(binding)?;
    anyhow::ensure!(bytes.len() <= 768, "certificate binding is too large");
    Ok(format!("cog-v1:{}", URL_SAFE_NO_PAD.encode(bytes)))
}

pub fn decode_binding(key_id: &str) -> anyhow::Result<Binding> {
    let encoded = key_id
        .strip_prefix("cog-v1:")
        .ok_or_else(|| anyhow::anyhow!("unknown certificate binding version"))?;
    anyhow::ensure!(encoded.len() <= 1024, "certificate binding is too large");
    let binding: Binding = serde_json::from_slice(&URL_SAFE_NO_PAD.decode(encoded)?)?;
    anyhow::ensure!(binding.version == 1, "unknown certificate binding version");
    Ok(binding)
}

pub fn generate_key() -> anyhow::Result<PrivateKey> {
    Ok(PrivateKey::random(
        &mut rand::rngs::OsRng,
        Algorithm::Ed25519,
    )?)
}

pub fn encode_private(key: &PrivateKey) -> anyhow::Result<Vec<u8>> {
    Ok(key.to_openssh(LineEnding::LF)?.as_bytes().to_vec())
}

pub fn decode_private(bytes: &[u8]) -> anyhow::Result<PrivateKey> {
    Ok(PrivateKey::from_openssh(bytes)?)
}

pub fn sign(
    ca: &PrivateKey,
    subject: &PublicKey,
    binding: &Binding,
    serial: u64,
) -> anyhow::Result<String> {
    let valid_after = binding.issued_at.saturating_sub(30) as u64;
    let valid_before = binding.expires_at as u64;
    let mut builder = certificate::Builder::new_with_random_nonce(
        &mut rand::rngs::OsRng,
        subject.key_data().clone(),
        valid_after,
        valid_before,
    )?;
    builder
        .serial(serial)?
        .cert_type(certificate::CertType::User)?
        .key_id(encode_binding(binding)?)?
        .valid_principal(PRINCIPAL)?;
    // Intentionally add no OpenSSH permission extensions. In particular this
    // omits agent/port/X11 forwarding, PTY, user-rc, and arbitrary environment.
    Ok(builder.sign(ca)?.to_openssh()?)
}

/// Parse and cryptographically verify a COG user certificate before its
/// binding is trusted by a downstream transport.
pub fn verify_certificate(
    encoded: &str,
    ca: &PublicKey,
    subject: &PublicKey,
    now: i64,
) -> anyhow::Result<Binding> {
    let certificate = ssh_key::Certificate::from_openssh(encoded)
        .map_err(|_| anyhow::anyhow!("invalid OpenSSH certificate"))?;
    let ca_fingerprint = ca.fingerprint(ssh_key::HashAlg::Sha256);
    certificate
        .validate_at(
            now.try_into()
                .map_err(|_| anyhow::anyhow!("invalid time"))?,
            [&ca_fingerprint],
        )
        .map_err(|_| anyhow::anyhow!("SSH certificate verification failed"))?;
    let binding = verify_certificate_fields(&certificate, subject)?;
    anyhow::ensure!(binding.issued_at <= now, "SSH certificate is not yet valid");
    anyhow::ensure!(binding.expires_at > now, "SSH certificate has expired");
    Ok(binding)
}

/// Verify a previously issued COG certificate without requiring it to still
/// be inside its validity window. This is only for renewal: the signature,
/// durable CA, subject key, and signed binding are still fully checked.
pub fn verify_certificate_for_renewal(
    encoded: &str,
    ca: &PublicKey,
    subject: &PublicKey,
) -> anyhow::Result<Binding> {
    let certificate = ssh_key::Certificate::from_openssh(encoded)
        .map_err(|_| anyhow::anyhow!("invalid OpenSSH certificate"))?;
    anyhow::ensure!(
        certificate.valid_before() > certificate.valid_after(),
        "SSH certificate validity window is invalid"
    );
    let ca_fingerprint = ca.fingerprint(ssh_key::HashAlg::Sha256);
    certificate
        .validate_at(certificate.valid_after(), [&ca_fingerprint])
        .map_err(|_| anyhow::anyhow!("SSH certificate verification failed"))?;
    verify_certificate_fields(&certificate, subject)
}

fn verify_certificate_fields(
    certificate: &ssh_key::Certificate,
    subject: &PublicKey,
) -> anyhow::Result<Binding> {
    anyhow::ensure!(
        certificate.cert_type() == certificate::CertType::User,
        "SSH certificate is not a user certificate"
    );
    anyhow::ensure!(
        certificate.valid_principals() == [PRINCIPAL],
        "SSH certificate has invalid principals"
    );
    anyhow::ensure!(
        certificate.public_key() == subject.key_data(),
        "SSH certificate does not match the authenticated public key"
    );
    anyhow::ensure!(
        certificate.critical_options().is_empty() && certificate.extensions().is_empty(),
        "SSH certificate contains unsupported permissions"
    );
    let binding = decode_binding(certificate.key_id())?;
    anyhow::ensure!(
        binding.issued_at < binding.expires_at,
        "SSH certificate binding validity window is invalid"
    );
    let bound_valid_after = u64::try_from(binding.issued_at.saturating_sub(30))
        .map_err(|_| anyhow::anyhow!("SSH certificate binding start time is invalid"))?;
    let bound_valid_before = u64::try_from(binding.expires_at)
        .map_err(|_| anyhow::anyhow!("SSH certificate binding expiry time is invalid"))?;
    anyhow::ensure!(
        certificate.valid_after() == bound_valid_after
            && certificate.valid_before() == bound_valid_before,
        "SSH certificate validity does not match its binding"
    );
    anyhow::ensure!(
        binding.fingerprint == fingerprint(subject),
        "SSH certificate fingerprint binding does not match"
    );
    anyhow::ensure!(
        matches!(binding.permission.as_str(), "read" | "write"),
        "SSH certificate permission is invalid"
    );
    anyhow::ensure!(
        crate::git::valid_repository_id(&binding.repository_id),
        "SSH certificate repository binding is invalid"
    );
    Ok(binding)
}

pub fn verify_certificate_with_durable_cas(
    encoded: &str,
    db: &Database,
    subject: &PublicKey,
    now: i64,
) -> anyhow::Result<Binding> {
    let mut last_error = None;
    for record in db.ssh_keys()?.into_iter().filter(|record| {
        record.purpose == "user_ca"
            && (record.active || record.retirement_time.is_some_and(|until| until > now))
    }) {
        let ca = PublicKey::from_openssh(&record.public_key)
            .map_err(|_| anyhow::anyhow!("durable SSH CA public key is unreadable"))?;
        match verify_certificate(encoded, &ca, subject, now) {
            Ok(binding) => return Ok(binding),
            Err(error) => last_error = Some(error),
        }
    }
    Err(last_error.unwrap_or_else(|| anyhow::anyhow!("no valid SSH user CA is available")))
}

pub fn verify_certificate_for_renewal_with_durable_cas(
    encoded: &str,
    db: &Database,
    subject: &PublicKey,
    now: i64,
) -> anyhow::Result<Binding> {
    let mut last_error = None;
    for record in db.ssh_keys()?.into_iter().filter(|record| {
        record.purpose == "user_ca"
            && (record.active || record.retirement_time.is_some_and(|until| until > now))
    }) {
        let ca = PublicKey::from_openssh(&record.public_key)
            .map_err(|_| anyhow::anyhow!("durable SSH CA public key is unreadable"))?;
        match verify_certificate_for_renewal(encoded, &ca, subject) {
            Ok(binding) => return Ok(binding),
            Err(error) => last_error = Some(error),
        }
    }
    Err(last_error.unwrap_or_else(|| anyhow::anyhow!("no valid SSH user CA is available")))
}

pub fn stable_serial(issuance_id: &str) -> u64 {
    let digest = Sha256::digest(issuance_id.as_bytes());
    u64::from_be_bytes(digest[..8].try_into().expect("eight-byte digest prefix"))
}
